name: CI
on:
  push:
    branches:
      - feat_webp_transform_20221018



jobs:
  build-deploy:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: npm install
    - run: npm run clean
    - run: npm run build
    - run: npm run coverage
    

    - name: Create Coverage Badges
      uses: jaywcjlove/coverage-badges-cli@main
    - run: cp -rp coverage build